version: "3.7"
services:
  database:
    image: mongo
    container_name: faceshuttermongo
    ports:
      - 27017:27017
    volumes:
      - data:/data/db
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=1234
    restart: always
    networks:
      - faceshutter
  fastapi:
    build: .
    container_name: fastapi
    restart: always
    ports:
      - "8000:8000"
    depends_on:
      - database
    networks:
      - faceshutter  
    environment:
      - PYTHONUNBUFFERED=1
      - UVICORN_LIFESPAN_ON=1
  fontend:
    build: ./fontend/
    container_name: fontend
    ports:
      - 3000:80
    depends_on:
      - fastapi
    networks:
      - faceshutter
    restart: unless-stopped
  nginx:
    build: ./nginx/
    image: nginx:alpine
    ports:
      - 80:80
    depends_on:
      - fontend
    networks:
      - faceshutter
    restart: unless-stopped
volumes:
  data:
networks:
  faceshutter:
    driver: bridge
