version: "3.7"
services:
  database:
    image: mysql:5.7
    platform: linux/x86_64
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: faceshutter
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - "3306:3306"
    volumes:
      - data:/var/lib/mysql
    networks:
      - faceshutter
    restart: always

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    platform: linux/amd64
    environment:
      PMA_HOST: database
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "8080:80"
    depends_on:
      - database
    networks:
      - faceshutter
    restart: always

networks:
  faceshutter:
    driver: bridge

volumes:
  data:
