version: "3.7"
services:
  database:
    image: mongo
    container_name: faceshuttermongo
    ports:
      - 27017:27017
    volumes:
      - data:/data/db
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=1234
    restart: always
    networks:
      - faceshutter

volumes:
  data:
networks:
  faceshutter:
    driver: bridge